services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=fabricio'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4'

    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=password'
      - 'PGADMIN_LISTEN_PORT=8001'
    ports:
      - '8001:8001'
    depends_on:
      - 'postgres'
      